const strings = {
  WAKE_LOCK_MESSAGE_ACTION_BUTTON: 'WAKE_LOCK_MESSAGE_ACTION_BUTTON',
  WAKE_LOCK_MESSAGE_ENABLED: 'WAKE_LOCK_MESSAGE_ENABLED',
  WAKE_LOCK_MESSAGE_DISABLED: 'WAKE_LOCK_MESSAGE_DISABLED',
  WAKE_LOCK_MODAL_CLARIFICATION: 'WAKE_LOCK_MODAL_CLARIFICATION',
  WAKE_LOCK_MODAL_CLOSE_BUTTON: 'WAKE_LOCK_MODAL_CLOSE_BUTTON',
  WAKE_LOCK_MODAL_FEATURE: 'WAKE_LOCK_MODAL_FEATURE',
  WAKE_LOCK_MODAL_PHONE: 'WAKE_LOCK_MODAL_PHONE',
  WAKE_LOCK_MODAL_TITLE: 'WAKE_LOCK_MODAL_TITLE',
};

export default strings;
