const strings = {
  WAKE_LOCK_MESSAGE_ACTION_BUTTON: 'WAKE_LOCK_MESSAGE_ACTION_BUTTON',
  WAKE_LOCK_MESSAGE_ENABLED: 'WAKE_LOCK_MESSAGE_ENABLED',
  WAKE_LOCK_MESSAGE_DISABLED: 'WAKE_LOCK_MESSAGE_DISABLED',
};

export default strings;
