const strings = {
  INSTRUCTIONS_MODAL_CLOSE_BUTTON: 'INSTRUCTIONS_MODAL_CLOSE_BUTTON',
  INSTRUCTIONS_MODAL_TEXT: 'INSTRUCTIONS_MODAL_TEXT',
  INSTRUCTIONS_MODAL_TITLE: 'INSTRUCTIONS_MODAL_TITLE',
  LANG_EN_US: 'LANG_EN_US',
  LANG_ES_ES: 'LANG_ES_ES',
  LANGUAGE_MODAL_CLOSE_BUTTON: 'LANGUAGE_MODAL_CLOSE_BUTTON',
  LANGUAGE_MODAL_TITLE: 'LANGUAGE_MODAL_TITLE',
  WAKE_LOCK_MODAL_CLOSE_BUTTON: 'WAKE_LOCK_MODAL_CLOSE_BUTTON',
  WAKE_LOCK_MODAL_FEATURE: 'WAKE_LOCK_MODAL_FEATURE',
  WAKE_LOCK_MODAL_PHONE: 'WAKE_LOCK_MODAL_PHONE',
  WAKE_LOCK_MODAL_SUPPORT: 'WAKE_LOCK_MODAL_SUPPORT',
  WAKE_LOCK_MODAL_TITLE: 'WAKE_LOCK_MODAL_TITLE',
  WAKE_LOCK_STATUS_ENABLED: 'WAKE_LOCK_STATUS_ENABLED',
  WAKE_LOCK_STATUS_DISABLED: 'WAKE_LOCK_STATUS_DISABLED',
};

export default strings;
